### ISSUE TITLE
Cannot import with deno

### ISSUE THREAD

**Issue by SirJosh3917** [neuledge/computed-types#30]
> Uncaught Error: Import 'https://deno.land/x/computed_types/src/array' failed: 404 Not Found

**Comment by moshest** [comment]
Looks like there is no way currently to have both Node.js and Deno code together: https://github.com/Microsoft/TypeScript/issues/27481

I can bundle this library on deployment using rollup and provide a bundle link using [jsdelivr.com](https://www.jsdelivr.com), but the output file will be `.js` instead of `.ts`.

Anyone know what's the right approach here?

**Comment by moshest** [comment]
Solve it using [Pika CDN](https://www.pika.dev/npm/computed-types)
